[build]
  base = "."
  command = "npm run build"
  publish = "out"
  
# Disable automatic Python detection
[build.environment]
  NETLIFY_USE_PIP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

